### ISSUE TITLE
Retrieve lanelet in the opposite direction of the same road?

### ISSUE THREAD

**Issue by corot** [fzi-forschungszentrum-informatik/Lanelet2#100]
Hi, I'm trying to retrieve the lanelet in the opposite direction of the same road, as here:

![image](https://user-images.githubusercontent.com/322610/77872124-0943b000-7281-11ea-99c1-2cdb68fac3e7.png)

As you can see, lanelets of both directions share a common line string:

![image](https://user-images.githubusercontent.com/322610/77872160-25475180-7281-11ea-8d63-ed616bac3492.png)

But when querying routing graph with besides, or adjacentLeft/Right I get nothing!

So what's the proper way to retrieve the opposite direction lanelet of a given lanelet?
Thanks!

**Comment by poggenhans** [comment]
By default, the adjacentLeft/Right property only works for Lanelet2 that are drivable in the same direction.

There are two ways to do what you want. The simplest solution would be to just query the LaneletMap for Lanelets using the Linestring: `Lanelets lanelets = laneletMap.laneletLayer.findUsages(lanelet.leftBound().invert());`. The invert is necessary, because the orientation of the linestring matters.

If you want the RoutingGraph to work as you expected, you could instanciate it with your own TrafficRule object by inheriting from one in `lanelet2_traffic_rules` and override it so that driving on lanelets is allowed in the opposite direction but no lane change is possible to this Lanelet.

**Comment by corot** [comment]
Thanks a lot. First option works for me.
