### ISSUE TITLE
[Question] Can Lanelet2 static build?

### ISSUE THREAD

**Issue by DarrenWong** [fzi-forschungszentrum-informatik/Lanelet2#103]
I want to use the lib as static lib by others project,  shared lib xx.so is ok, but is there a way to build it as static lib?
I try to add below args but failed in the catkin build. Only can build out liblanelet2_core.a.
`catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DBUILD_SHARED_LIBS=OFF `

shared build ok:
![Screenshot from 2020-04-02 18-22-23](https://user-images.githubusercontent.com/5771106/78241042-61451580-7512-11ea-9b04-f677d52108a0.png)
static build not working:
![Screenshot from 2020-04-02 18-23-20](https://user-images.githubusercontent.com/5771106/78241079-6efa9b00-7512-11ea-9b54-597dcd4c94f5.png)
remove  

`#mrt_install(PROGRAMS scripts FILES res data ${PROJECT_INSTALL_FILES})
`

![Screenshot from 2020-04-02 18-34-53](https://user-images.githubusercontent.com/5771106/78241210-a0736680-7512-11ea-982a-8f1e083cece7.png)

**Comment by poggenhans** [comment]
Seems like you ran into [this cmake bug](https://gitlab.kitware.com/cmake/cmake/issues/15415#note_634114), where private dependencies of a library target suddenly need to be exported when you turn it into a static library

Anyways, static builds are NOT supported anyways. This is because our plugin concept for extending `lanelet_io` and regulatory elements relies on static symbols being present so that they are registered properly for the factory methods.

These symbols are not pulled in when linking statically, and therefore simple things like loading a map will not work, because the plugin for the respective file extension is not registered.

**Comment by DarrenWong** [comment]
Got it and thanks,   shared lib is also ok. 
Might  just rebuild once on the new environment if the dependencies  do not install in the same place
