### ISSUE TITLE
ROS 2 Support

### ISSUE THREAD

**Issue by JWhitleyWork** [fzi-forschungszentrum-informatik/Lanelet2#112]
Is there currently any intent to support building in ROS 2? If not, would you be open to a pull request which makes these packages into "hybrid" ROS1/2 packages so they can be built in both?

**Comment by poggenhans** [comment]
Right now, we have no intention of building for ROS2. But we wouldn't mind a PR, of course. I think it shouldn't be too difficult. Lanelet2 only has a `test_depend` to `rosbash` in `lanelet2_examples`, because the unittest executes the examples using `rosrun`. This is convenient, but I suppose there are ways to solve this without the help of ROS.

I am not sure if ROS2 has any build-system specific requirements, in that case it might be necessary to patch `mrt_cmake_modules`.

**Comment by JWhitleyWork** [comment]
@poggenhans Most of the functionality included in `mrt_cmake_modules` is already available as new `auto` macros in ROS 2. I'll be using these in my PR so you can see what I mean. Thanks! I'll close this issue once ROS 2 support has been ipmlemented.

**Comment by poggenhans** [comment]
Yes that might be true. The long-term plan for `mrt_cmake_modules` is to turn it into something that works independently of catkin and ament with both ROS versions (and build systems). Then all our packages would automatically be turned into hybrid ROS1/ROS2 packages.

Since this migration will be a lot of work I would favour a minimal-invasive solution that avoids touching lanelet2's CMakeLists and does only the necessary changes in mrt_cmake_modules. But my understanding of the ROS2's build system is not deep enough to know if such a solution is possible.

**Comment by poggenhans** [comment]
I played a little with `colcon` and `lanelet2` and it turned out the changes in `mrt_cmake_modules` where not as difficult as I expected. Most of the changes went into handling python code/bindings and setting up the environment hooks correctly. The C++ part and the dependency resolution worked mostly out of the box.

If you want to have a look, the changes are on a branch named `ament_support` in both `mrt_make_modules` and here. With that I was able to successfully run the tests.

One thing that is not ideal yet is the lanelet2 metapackage. It seems ros2 dropped support for metapackages, and ros1 complains if the CMakeLists.txt and the package.xml deviate from the "ideal" one. I would like to keep it as a metapackage to remain fully compatible to ROS1 (our internal tooling relies on that too), but it seems impossible.

**Comment by JWhitleyWork** [comment]
@poggens With your modifications, did you make `mrt_cmake_modules` and `Lanelet2` use _only_ ament or both _ament_ and _catkin_ based on the environment (a hybrid)? 

My work has been on creating a hybrid which can build in both. See https://github.com/JWhitleyWork/Lanelet2/tree/ros2-hybrid. The metapackage tag has been problematic for me too. However, I found that it isn't strictly necessary. If you just leave the package with the appropriate `exec_depends`, then it functionally works the same.

My version does not use `mrt_cmake_modules` as much of its functionality is now available in `ament_cmake_auto`. Check out my version and let me know if you would rather move forward with your method or mine. Both still require a bit of work (a couple of tests fail on mine and yours is missing some required changes in CMake).

**Comment by poggenhans** [comment]
They are now both hybrid based on the value of `ROS_VERSION`.

I've looked at your version. It goes rather the way I wanted to avoid when I said that I would prefer a solution that does not touch the CMakeLists of lanelet2 as much as possible. This may sound strange, because CMakeLists are usually a place where no coding standards are respected, but should you ever be responsible for all of the few hundred CMakeList files in your organization, you will also become a fan of standardized CMakeList files.

> Both still require a bit of work (a couple of tests fail on mine and yours is missing some required changes in CMake).

What are the changes I was missing? Yesterday was my first contact with colcon, it would have been a miracle if I got everything right.

> The metapackage tag has been problematic for me too. However, I found that it isn't strictly necessary. 

According to [the miration guide](https://index.ros.org/doc/ros2/Contributing/Migration-Guide/#id2) it is not necessary *for ROS2*. But I am not sure about ROS1. Afaik it is still in use, e.g. for generating and grouping the documentation of the sub-packages. And as I said, the tooling in my organization relies on it too.

**Comment by JWhitleyWork** [comment]
> What are the changes I was missing?

Specifically the one I noticed is that the testing variable has changed from `CATKIN_ENABLE_TESTING` to `BUILD_TESTING`. To keep the CMakeLists.txt files consistent, you can probably change the `if` to `if(CATKIN_EANBLE_TESTING OR BUILD_TESTING)`.

**Comment by poggenhans** [comment]
Yes, that is a flaw in our current template. For the moment I fixed that in `mrt_cmake_modules` by setting `CATKIN_ENABLE_TESTING` to true based on the value of `BUILD_TESTING` in ROS2.

Once we know what other changes have to be made, I will update our template and subsequently update the files in `lanelet2`.

**Comment by JWhitleyWork** [comment]
I will test building the ament-aware version within our stack and let you know if we run into any problems.

**Comment by JWhitleyWork** [comment]
@poggenhans So, everything seems to build OK but *many* of the tests fail in `lanelet2_routing`, `lanelet2_io`, and `lanelet2_validation`.

**Comment by poggenhans** [comment]
Ok, that is something at least something. Can it be that cmake is building static libraries instead of shared? The plugin system that lanelet2 uses is not prepared for static libraries.

I am not sure if I got it right how shared libraries are supposed to be built with colcon. Catkin just silently passes `-DBUILD_SHARED_LIBS=On` to cmake. Colcon doesn't seem to do that, I had to specify the flag manually to make it work. Or am I missing some magic in `ament_cmake` that makes that work?

**Comment by JWhitleyWork** [comment]
@poggenhans You have to supply the keyword `SHARED` to the `add_library` command but that's it for making them build shared libraries.

In addition, the file `cmake/Templates/python_api_install.py.in` uses a lot of CATKIN variables still, which means the Python modules won't be installed correctly using it.

Can you possibly provide me with your standard CMake template? I would like to create one that can handle ROS 1 with `mrt_cmake_modules` and ROS 2 with just `ament` macros. I truly believe that much of the functionality that you've provided in `mrt_cmake_modules` is available as macros in the `ament` build system.

**Comment by poggenhans** [comment]
> You have to supply the keyword SHARED to the add_library command but that's it for making them build shared libraries.

That would force Cmake to do the right thing, but it is generally not advised to do so because it deprives the user of the option to choose. I found out the "magic" I was missing was `ament_cmake_ros`. It seems to exist mostly only for the purpose of setting `BUILD_SHARED_LIBS` to `ON` so that everything works as expected in ROS2. I replicated this behaviour in `mrt_cmake_modules`. With that, your builds should do better now, I hope.

> In addition, the file cmake/Templates/python_api_install.py.in uses a lot of CATKIN variables still, which means the Python modules won't be installed correctly using it.

The template is only used with ROS1 because it has a very special way of installing python stuff (symlinks and so on). For ROS2 python files are simply copied to the python install directory just as ament does it. That worked fine in my tests.

> Can you possibly provide me with your standard CMake template?

The template is [provided by mrt_cmake_modules](https://github.com/KIT-MRT/mrt_cmake_modules/blob/master/ci_templates/CMakeLists.txt). The [Readme](https://github.com/KIT-MRT/mrt_cmake_modules#getting-started) explains how to use it. 

ament and mrt_cmake_modules are similar in their philosophy but have different features and different ways they archive that. Because we want our packages to behave the same way in ROS2 they work in ROS1, using ament is not really an option for us. Some differences include:
- mrt_cmake_modules is even more simpler than ament by providing one CMakeFile that is never to be touched in any project. Basically all calls to CMake and Catkin are wrapped, allowing us to modernize our code with newer cmake versions without having to be backwards compatible. All updates to this template just have the goal to make it better at wrapping CMake and Catkin (and potentially ament).
- It supports building python bindings
- It can analyze code coverage of cpp and python code
- It supports gcc's sanitizers
- It detects and runs tests automatically
- It supports setting a system wide cmake config file for ensuring all projects using it are built with the exact same C++ standard and compiler/warning flags.
- Running linters is enabled through cmake flags instead of explicit opt-in in the CMakeLists

Of course `ament` has features `mrt_cmake_modules` hasn't, like better Windows support, more and different linters and a larger community to fix things. But as things stand right now, it is much less work to make the `mrt_cmake_modules` behave like `ament` by changing some of it's internals than to adapt the CMakeLists template to make `ament` behave like `mrt_cmake_modules`.

**Comment by JWhitleyWork** [comment]
@poggenhans I have tested importing `mrt_cmake_modules` and `Lanelet2` into our stack from the current `ament_support` branches and everything appears to build and test correctly. I'm going to add the current versions as `git subtree`s to our repo. Do you have an ETA on when you might merge these changes to `master` for either of the repos?

**Comment by JWhitleyWork** [comment]
FYI - I do get a warning from CMake that the variable `CATKIN_INSTALL_INTO_PREFIX_ROOT` was unused by the project.

**Comment by JWhitleyWork** [comment]
I have run into a few issues with the build. The first is that, in the main CMakeLists.txt for `mrt_cmake_modules`, the environmental variable ROS_VERSION is used without prerequisites. Your CMakeLists must first `find_package(ros_environment)` and you have to have it as a build dependency too.

Second, I get the following in `lanelet2_routing` when running `colcon test-result --verbose`:

```

 build/lanelet2_routing/test_results/lanelet2_routing/gtest-lanelet2_routing-gtest-test_routing_visualization.xml: 10 tests, 0 errors, 2 failures, 0 skipped
 - GermanVehicleGraph GraphVizExportError
   <<< failure message
     /builds/autowarefoundation/autoware.auto/AutowareAuto/src/external/Lanelet2/lanelet2_routing/test/test_routing_visualization.cpp:47
     Expected: graph->exportGraphViz("/bla") throws an exception of type lanelet::ExportError.
       Actual: it throws nothing.
   >>>
 - GermanVehicleGraph GraphMLExportError
   <<< failure message
     /builds/autowarefoundation/autoware.auto/AutowareAuto/src/external/Lanelet2/lanelet2_routing/test/test_routing_visualization.cpp:62
     Expected: graph->exportGraphML("/place_that_doesnt_exist", RelationType::None) throws an exception of type lanelet::ExportError.
       Actual: it throws nothing.
   >>>
```

**Comment by poggenhans** [comment]
> Do you have an ETA on when you might merge these changes to master for either of the repos?

Good to hear my fix worked. I first want to solve the metapackage problem. I started a discussion on that on [ROS discourse](https://discourse.ros.org/t/building-hybrid-ros1-ros2-metapackages/14592).

> FYI - I do get a warning from CMake that the variable CATKIN_INSTALL_INTO_PREFIX_ROOT was unused by the project.

That seems to be normal. See https://github.com/colcon/colcon-ros/issues/83.

> The first is that, in the main CMakeLists.txt for mrt_cmake_modules, the environmental variable ROS_VERSION is used without prerequisites. Your CMakeLists must first find_package(ros_environment) and you have to have it as a build dependency too.

Thanks, I will look into that.

> Second, I get the following in lanelet2_routing when running colcon test-result --verbose

We have to improve these tests, I guess. Can it be you are testing in an environment where writing to "/" is not prohibited? The tests seem to rely on the assumption this is the case.

**Comment by JWhitleyWork** [comment]
The latest commit to `mrt_cmake_modules` has fixed the issues with dependency on `ros_environment` and using its variables in CMake files. However, the other two `lanelet2_routing` errors still exist. Do you have an ETA on when that one might be fixed?

I want to mention that I'm very glad for your help on this issue and really appreciate the work you've put into it. I will also see if I can troubleshoot that error and provide an MR.

**Comment by poggenhans** [comment]
Ah, sorry. I fixed that already but forgot to also push it to this repository. With 2bd4faf6baff4bcc0fc1718f1578c6e01ddcced2, the tests should be running.

**Comment by JWhitleyWork** [comment]
Thank you! It builds and the tests all pass!!! (even on `arm64`!). Thanks so much for your help. Keep me updated on when the packages are released for ROS Dashing (and eventually Foxy) so we can remove the `git subtree`s from our package. Let me know if I can be of any further help!

**Comment by JWhitleyWork** [comment]
@poggenhans Now that we have verified that this works in a ROS2 environment within a software stack, would it be possible for you to release `mrt_cmake_modules` and `lanelet2` to the ROS2 build farm? The process is exactly the same as for the ROS1 build farm but should be run for Dashing and Foxy.

**Comment by JWhitleyWork** [comment]
@poggenhans Any update on this? This is becoming increasingly important for Autoware Foundation projects.

**Comment by poggenhans** [comment]
We lost that a bit out of sight when we had to fix some python3 issues in the mrt_cmake_modules in the noetic release that had to be fixed and released first.

I created two PRs for `mrt_cmake_modules` in `eloquent` (https://github.com/ros/rosdistro/pull/26443) and `lanelet2` in `noetic` (https://github.com/ros/rosdistro/pull/26444) as test balloons. When they work, we can start to do the rest.

**Comment by JWhitleyWork** [comment]
@poggenhans Totally understand. Thanks! The AWF is currently working in Dashing so we would appreciate a PR to that distro as well but this is an excellent first step and I understand if you want to wait to make sure all of the jobs pass on Eloquent first. Thanks for your help!

**Comment by poggenhans** [comment]
Done with https://github.com/ros/rosdistro/pull/26790, https://github.com/ros/rosdistro/pull/26740 and https://github.com/ros/rosdistro/pull/26791
