### ISSUE TITLE
[Question] Custom regulatory element best practice

### ISSUE THREAD

**Issue by msmcconnell** [fzi-forschungszentrum-informatik/Lanelet2#118]
I am wondering if it is recommended to have 2 way to 1 way linking of RegulatoryElements and their parameters. Consider this situation
Lets say I have a DynamicSpeedLimit regulatory element and its value comes from a web server due to weather. Since this element is not associated with a physical object like a traffic sign there aren't parameters of the kind used in the examples. I would like to apply it to whole lanelets instead. Should I make the lanelets parameters and add the regulatory element to the lanelets (2 way linking) or should I only add the regulatory element to the lanelet and leave its parameter list empty (1 way linking)?

**Comment by poggenhans** [comment]
Conceptually, it is rather the job of the TrafficRules object to evaluate the true meaning of a regulatory element. The regulatory element just represents the information that is necessary to understand the rule and where it comes from (so that it is possible to reason about the consequences of map changes).

So for your case I would suggest implementing your own "DynamicSpeedLimit" aware TrafficRules. The DynamicSpeedLimit itself wouldn't have to be much different form the normal SpeedLimit. It just references the sign that says that the speed limit is weather dependent (if there is one).

**Comment by msmcconnell** [comment]
@poggenhans It sounds like you are recommending 1 way linking. So the lanelet references the regulatory element but the lanelet itself does not need to be a parameter of that element. Would you agree? The traffic rules interpretation of the element is really a question of identifying the stored speed limit value rather than how the element parameter list is structured.

**Comment by poggenhans** [comment]
Ah, now I think I understand your question. You want to express rules like "If it is wet on this lanelet, use that speed limit".

In that case, I guess in this case it could make sense to also make the lanelet(s) a parameter of the regulatory element. I wouldn't consider that as two-way linking because the lanelets used to determine if the condition is fulfilled wouldn't be the same as the ones for which the speed limit would be valid.

**Comment by msmcconnell** [comment]
That is more along the lines of what I am thinking. Seems like the rule of thumb then would be: if the existence or state of a specific lanelet impacts how the regulatory element is interpreted then the lanelet should be a parameter. If not, then the lanelet would just reference the regulatory element.

**Comment by poggenhans** [comment]
This issue has been inactive for a while. I'm assuming the original question has been answered.
