### ISSUE TITLE
regarding license terms

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#132]
I found out that Lanelet2 has BSD-3 Clause license, but mrt_cmake_modules has GPL v3.
Since Lanelet2 assumes that it uses mrt_cmake_modules, wouldn't this mean that all software that uses Lanelet2 must be released as GPLv3 license? Or is it okay since mrt_cmake_modules is a build tool?

I'm aware that one of maintainers of Lanelet2 also maintains mrt_cmake_modules, so I would like to ask if you have any plans of switching it to permissive license (e.g. BSD or Apache) or at minimum to weak copyleft (e.g. LGPL) license? Otherwise, it might be difficult to use Lanelet2 in our projects.

**Comment by poggenhans** [comment]
Actually, I was wondering how long it would take until someone raises a concerns about that.

From my point of view, since  `mrt_cmake_modules` are only CMake scripts, their license shouldn't affect the compiled binary of lanelet2. Only the generated cmake files could fall under GPL.

We will have to investigate if relicensing is possible.

**Comment by poggenhans** [comment]
mrt_cmake_modules is now BSD.
