### ISSUE TITLE
[Question] Docker import error

### ISSUE THREAD

**Issue by ConstantinB9** [fzi-forschungszentrum-informatik/Lanelet2#133]
I am trying to run the docker container using the lanelet2 image and starting a python script with lanelet2 dependencies alongside it. However I get an ImportError whenever I try to do so.

The process described in the tutorial works fine with me
```
docker run -it --rm lanelet2:latest /bin/bash # starts the docker image
python -c "import lanelet2"                   # quick check to see everything is fine
```

What I am looking for is a way to reduce this to a single step / command like so
```
docker run -it --rm lanelet2:latest python -c "import lanelet2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lanelet2
```
is there any workaround or solution which might let me achieve this?

**Comment by poggenhans** [comment]
To make that work you have to make sure the `setup.bash` is sourced. Usually the `.bashrc` would handle that, but since you are not in a login shell, it doesn't work.

You could do it like this: `docker run -it --rm lanelet2:latest /bin/bash -c "source /home/developer/workspace/devel/setup.bash && python -c \"import lanelet2\"`
