### ISSUE TITLE
[Question] How to retrieve the intersection areas from the laneletmap?

### ISSUE THREAD

**Issue by rodrigoqueiroz** [fzi-forschungszentrum-informatik/Lanelet2#143]
I'm not sure how to handle the following cases:
- From a route, retrieve lanelets that belong to intersections.
- Retrieve the entire intersection space (all lanelets sharing that intersection area, or junction).

**Comment by poggenhans** [comment]
Lanelet2 has a different notion of an "intersection" than what you are probably thinking of. It is hard to define what exactly constitutes an intersection area. Where exactly does it begin? Where does it end? Are sidewalks included? Pedestrian crossings? Bicycle lanes?

Therefore "Intersections" in lanelet2 are rather defined on the lanelet level as conflicts between lanelets, i.e. Lanelets that overlap. There are may ways to retrieve conflicting lanelets, e.g. by asking the RoutingGraph or directly from within the Route object if you are interested in conflicting lanelets for the same participant type or using the RoutingGraphContainer for conflicting lanelets between *different* participants (e.g. intersections between bicycles and vehicles).

If you are really interested in the intersection area as a whole, you would have to add that area manually, according to what you define as an intersection area and work with that, because there is most likely no way to infer that only by looking at the lanelets.
