### ISSUE TITLE
possiblePaths() wrong output 

### ISSUE THREAD

**Issue by ramizka** [fzi-forschungszentrum-informatik/Lanelet2#144]
We have 2 lanelets:  
 -> ID 1, length 60 meters long, lanelet1, next lanelet is ID 2
 -> ID 2, length 40 meters, lanelet2 (does not have any lanelets following)

graph.possiblePaths(lanelet1, 10, 0, false) - we would like to have path minimum 10 meters long.
We should have 1 LaneletPath including 2 lanelets. Ok. We got it.

graph.possiblePaths(lanelet1, 80, 0, false) - we would like to have path minimum 80 meters long.
We should have 1 LaneletPath including 2 lanelets. ERROR!

graph.possiblePaths(lanelet2, 10, 0, false) - we would like to have path minimum 10 meters long.
We should have 1 LaneletPath including original lanelet with ID 2.  ERROR! The only way to get original lanelet in case original lanelet does not have following lanelets is to set MinRoutingCost = 0.

So this is an error in graph routing. 

Map and Python script is provided. 
[example_lanelet2_graph_routing.zip](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/files/5064468/example_lanelet2_graph_routing.zip)

**Comment by poggenhans** [comment]
I am a bit surprised lanelet2 eats this map. Its not conforming to the OSM format and your lat/lon coordinates wrap the globe with 413° longitude... where did you get this map from?

To your question: Its not an error in the graph routing, its just a misunderstanding in how the RoutingCostDistance object calculates routing costs: Costs are always calculated from the center of the lanelet to the center of the next lanelet, in order to keep them symmetric.

In the case of your lanelets, the costs for driving from lanelet 1 to lanelet 2 is 50m, therefore there is no path of length 80m or more that brings you from the center of lanelet 1 to another lanelet. For lanelet2, there is obviously also no such path, because it has no successors.
