### ISSUE TITLE
[Question] Modeling dynamic environments

### ISSUE THREAD

**Issue by rowandempster** [fzi-forschungszentrum-informatik/Lanelet2#154]
Hi all,

First off amazing work with liblanelet and lanelet2, they have been crucial to the planning stack at my research group. 

My question is about pushing the limits of the logical model and the current library implementation with the goal of modeling dynamic aspects of the environment (ie anything you can't put into a static osm file, eg pedestrians & trash cans in the road). The rough idea my research group is exploring is how to create structured relationships between symbolic properties of the tracked objects, HD map, and occupancy grid that allows us to quickly and easily answer questions that are needed to decide on a behavior. The [RoadGraph](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.399.1691&rep=rep1&type=pdf) architecture describes one approach in some detail. 

We are pursuing the lanelet logical model and implied graph structure to serve as the "backbone" of the dynamic relation graph we are researching. To deepen my understanding of the logical model and test the feasibility of usage, I have a couple questions regarding customization points I have identified and how far these can be pushed:

1. Custom TrafficRules: One way I see to influence routing based on a dynamic environment is to implement a custom TrafficRule class which tests its predicates (eg `canPass`) based on dynamic environmental conditions (eg occupancy of lanelet). However, from my understanding, anytime the result of a TrafficRule predicates change, a new RoutingGraph must be created? There is no way to dynamically update the data that a TrafficRule tests its predicates on after it has been passed to a RoutingGraph?

2. Custom RegElem: To setup more complex relationships between tracked agents (eg pedestrians) and primitives, is it possible to dynamically instantiate custom RegElem classes? For example, a PedRegElem which refers to the lanelet(s) that the pedestrians movement is in conflict with? How to construct queries that extract useful information from those RegElem relationships is another question, maybe using the PathVisitor design to test how far along the current path we'll need to stop for a pedestrian?

Thanks for your time taken to consider my questions and how my research group's goal would fit into the lanelet model. If our extension investigation is something that intrigues you I am open to a longer dialog.

**Comment by poggenhans** [comment]
Your questions touch on many points that could lead to very interesting but also lengthy discussions. I will try to limit myself. Please note that this is also only my personal opinion.

Lanelet2 tries to separate things that we perceive as static (the road layout) from things that are dynamic (everything else). And it helps you handle the first thing by creating the routing graph for you which is a potentially costly operation, but - since it's static - only has to be done once. It does not help you so much with the second, because that depends on the current situation and on what your sensors are telling you. It just provides you (via `RegulatoryElements`) the information that is required to figure out what the "right" action is, given the current situation.

There might be cases where this separation is less clear (e.g. when you observe that parts of the road or the whole road is blocked), but even there are ways to make Lanelet2 handle that. A partly blocked road doesn't need replanning, you just search for a new lanelet path within your `Route`. For a fully blocked road it could make sense to instanciate a new `RoutingGraph`, but since this is a rare case I think it is justified that this kind of replanning takes a little longer.

So far the idea behind the implementation. To answer your questions directly:
1. I wouldn't recommend to use traffic rules for things that change while driving. The usual case is that during driving you discover that *less* options are available (never *more*), so usually you should be able to just constrain your queries to the existing routing graph by discarding results that you know are currently not feasible for whatever reason. It would not be much work to add functionality to the routing graph to add/remove existing edges, but then users you would have to remember to add them again once the situation changes, so I am not sure if that really helps to solve this.
2. I would recommend to implement your own way of modeling relations between participants and the map on top of lanelet2. If you use RegulatoryElements for that, the result would be that if you e.g. store the modified map, the participants that you have referenced will stored as well because lanelet2 doesn't know this relation was only a temporary one. That might be useful for debugging purposes, but generally not what you want. Also lanelet2 assumes that all its objects do not move, so any spacial queries will give wrong results because the `LaneletMap` caches the bounding box of the objects.

**Comment by rowandempster** [comment]
Thanks for your input, closing for now while we work through the prototype, will share results.
