### ISSUE TITLE
Question about Stop Signs

### ISSUE THREAD

**Issue by icolwell-as** [fzi-forschungszentrum-informatik/Lanelet2#156]
If my understanding of the Lanelet format is correct, there are 3 valid ways to represent a stop sign in Lanelet2 format:
1. AllWayStop regulatory element. Each `refers` role points to a linestring representing a stop sign.
2. TrafficSign regulatory element. Each `refers` role points to a linestring representing a stop sign, assuming the `subtype` role is using the code for a stop sign.
3. RightOfWay regulatory element. A `ref_line` defines the stopline for road users to stop at while yielding.

My question/confusion is why RightOfWay doesn't have an optional `refers` role to point at stop signs?
Is option 3 technically not the correct way to represent a single stop sign?

If I wanted to represent the following 2-way stop intersection
![2_way_stop](https://user-images.githubusercontent.com/48106342/97467058-2f662700-191a-11eb-9b1c-6580fbcf5f5c.jpeg)

Would I have to put in 2 TrafficSigns reg elems, and 1 RightOfWay reg elem?

**Comment by poggenhans** [comment]
RightOfWay is the right thing to use. That it has no convenient functions for accessing the traffic signs in its `refers` role doesn't mean it is not allowed to have them. You can still get them, if you want (`regelem->getParameters<lanelet::ConstLineString3d>(RoleName::Refers)`).
  

The reason it doesn't have convenient accessors for the traffic signs is that we couldn't settle for a good way of modeling the relation between signs and lanelets, so that is possible to answer the question "which sign(s) are for which lanelet". So we just kept that unsolved until someone comes around with a good idea.

**Comment by icolwell-as** [comment]
Thanks @poggenhans for the response and code snippet! I've been using the python API recently and I'm still new to it, is there any similar way to get the refers role from a RightOfWay element in python?

**Comment by poggenhans** [comment]
Simply `regelem.parameters["refers"]`. The result will be a list of potentially Points, Linestrings or Polygons.

**Comment by icolwell-as** [comment]
Awesome thanks!
