### ISSUE TITLE
joining new lanes to existing lanes require the existing lane to split into two lanes

### ISSUE THREAD

**Issue by dinesh3367** [fzi-forschungszentrum-informatik/Lanelet2#164]
hello Team,

I am trying to add new lanes to existing lanelet map, with which we noticed that when trying to add a new lane that is near to an existing lane would require us to split the existing lane into two for connecting the new lane to generate a route via the new lanes

![image](https://user-images.githubusercontent.com/31798603/100247215-1b850380-2f60-11eb-9f29-1a3373bfaa3f.png)

the above picture shows that we have an intersection at the point where we wanted to join a new lane to an existing lanelet2 map. with the intersection we can generate a route through lanelet1 & lanelet3

Whereas when we join the new lane to an existing lane in this fashion

![image](https://user-images.githubusercontent.com/31798603/100247769-b251c000-2f60-11eb-808f-89d608e4d6dd.png)

the route generation logic says no route through lanelet1 & lanelet3

so this means we should be splitting the existing lane into two lane when we wanted to join a new lane into a middle node of an existing lane ?? is that correct or we missing something here ??

**Comment by poggenhans** [comment]
This is correct. The semantics of routing in lanelets mean that if it is possible to drive from lanelet1 to lanelet3, it must be possible from *everywhere*. How could you get a corridor for driving from a route if this assumption does not hold?

Since JOSM was not made for lanelet2, mapping some things can be tedious. But if have this case regularly, why don't you write a small python program based on lanelet2 that splits these lanelets for you?

**Comment by dinesh3367** [comment]
Thanks for confirming our understanding. Yeah we could plan for identifying the nearest point in the existing lanelet and split the lanelet into two for creating the intersection.
