### ISSUE TITLE
shortest path through a lane change is delivering the output route like this 

### ISSUE THREAD

**Issue by dinesh3367** [fzi-forschungszentrum-informatik/Lanelet2#166]
is this how the lanelet api produces a shortest path if we detect a lane change to reach the destination ??

![image](https://user-images.githubusercontent.com/31798603/100355912-8db91f00-3018-11eb-9122-27751f362b5d.png)

am i missing anything here ??

please support

Thanks

**Comment by poggenhans** [comment]
I think this will make more sense to you if you think about this on the Lanelet level, not on the centerline level. As stated in the [docs](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_routing#route-vs-path-vs-sequence): If you ask for a path that includes lane changes, you will get a series of Lanelets, that could potentially be adjacent left or right (where the lane change occurs). How you handle this lane change is up to you. Lanelet2 can not help you here, because this depends on more factors that just the map (i.e. the current traffic).

Just computing the centerline from the path will not give you the correct result, as you observed. This will just give the centerline of all lanelets linked together.

**Comment by dinesh3367** [comment]
Thank you once again for confirming the understanding. Agree with this fact that machine has to handle the lane swap based on the traffic conditions and other factors while moving.
