### ISSUE TITLE
Python argument types error

### ISSUE THREAD

**Issue by icolwell-as** [fzi-forschungszentrum-informatik/Lanelet2#168]
I came across the following error when try to use the Python API.
```
Traceback (most recent call last):
  File "./tutorial.py", line 168, in <module>
    tutorial()
  File "./tutorial.py", line 22, in tutorial
    part6routing()
  File "./tutorial.py", line 122, in part6routing
    lanes = map.laneletLayer.findUsages(following[0].leftBound)
Boost.Python.ArgumentError: Python argument types in
    LaneletLayer.findUsages(LaneletLayer, ConstLineString3d)
did not match C++ signature:
    findUsages(lanelet::LaneletLayer {lvalue}, lanelet::LineString3d {lvalue})
    findUsages(lanelet::LaneletLayer {lvalue}, std::shared_ptr<lanelet::RegulatoryElement> {lvalue})
```

I was able to reproduce the error by adding the following 2 lines to the tutorial.py after line 120:

```
120 assert len(graph.possiblePaths(lanelet, 100, 0, False)) == 1
121
122 following = graph.following(lanelet)
123 lanes = map.laneletLayer.findUsages(following[0].leftBound)
124
125 # here we query a route through the lanelets and get all the vehicle
```

This raises two questions:

1. In general, how does the Python API handle const vs. non-const lanelet object types? Should they mostly be interchangeable from a read-only perspective?
2. Am I doing something wrong in the above code sample? or is the Python API missing something to allow `findUsages` to handle `ConstLineString3d` types?

Thanks!

**Comment by poggenhans** [comment]
In general the python api tries to give the user normal, mutable types, since immutable types do not really fit well to the python philosophy. But there are a few cases (especally in the routing package, since it almost exclusively uses the const versions) where it cannot hide this. Non-const typesinherit from their const counterparts and can therefore be used wherever const types can be used, but not the other way around.

You are not doing something wrong, `findUsages` is just implemented to handle const types (even though it could). I'll look into fixing this.

**Comment by icolwell-as** [comment]
Thanks @poggenhans for the explanation! 

For anyone who may be curious, I can temporarily work around this issue by looking up the non-const entity and using that instead.
```
non_const_lanelet = map.laneletLayer[const_lanelet.id]
```
