### ISSUE TITLE
ubuntu 16.04

### ISSUE THREAD

**Issue by Shelfcol** [fzi-forschungszentrum-informatik/Lanelet2#17]
Does lanelet2 support  ubuntu14.04?

**Comment by poggenhans** [comment]
Are you asking about 14.04 or 16.04? Your title and your question are not consistent...

16.04 is supported. We don't actively support 14.04, but since Lanelet2 to has only a few dependencies, there should be ways to make it run.

I would expect issues due to the old boost version and the old version of Gcc that is installed by default. At least 5.4 is required to compile Lanelet2.

**Comment by Shelfcol** [comment]
sorry,I just want to ask about ubuntu14.04,the title is wrong.Actually I only install gcc-5.1.0,I will try gcc-5.4 later.Thank you.
