### ISSUE TITLE
Illegeal Instruction

### ISSUE THREAD

**Issue by busch1987** [fzi-forschungszentrum-informatik/Lanelet2#18]
Hello, 
I successfully build my program including Lanlets2 at a virtual machine at my system.
After I export and import the VM at another system, I get a "Illegal Instruction” error at the program start. My program was stable at the second system in this VM without lanlet2 and catkin build. 
Any idea why there is this difference between the systems?

**Comment by poggenhans** [comment]
By default, Lanelet2 is configured to be optimized for the sandybridge architecture, because it is the first CPU generation that supported AVX instructions. If you execute it on a system that is older than that or using and AMD CPU, you get this error.

To mitigate that, you can initialize your workspace by setting the CMake variable `MRT_ARCH` to a value that is understood as value for the `-march` flag in GCC. E.g. running `catkin config --cmake-args -DMRT_ARCH=x86-64` on a clean workspace will cause CMake to compile for the most generic but also slowest CPU instruction set.

**Comment by busch1987** [comment]
Thank you for the fast reply, it fixed the problem instantly!
