### ISSUE TITLE
Incorrect UTM zone when extracting cooridinates from Lanelet

### ISSUE THREAD

**Issue by miropipa** [fzi-forschungszentrum-informatik/Lanelet2#181]
I plotted my lanelets on JOSM in a street with a UTM coordinates of 363456 143662, at the zone 48N. I then wrote a function which publishes the coordinates of the centerline points on a text file. Given as followed: 

for(const ConstPoint3d& point : lanelet.centerline())
    {
        outputFile << point.x() << " " << point.y() << "\n";
    }

However, the resulting easting UTM coordinates are way too off from where I have ploted the lanelets.(1.1549e+07 144564 .etc), which led me to suspect that the UTM zone referenced might be wrong. As the written easting coordinates are so large in values, they have now become redundant as they all share the same values in the text file.

Is there a way to rectify this problem such that the published coordinates reflects the UTM zone correctly?

**Comment by poggenhans** [comment]
I don't think this is a problem with the UTM zone. This rather looks like a misunderstanding in how the UTM projector works.

By default, all projectors in Lanelet2 work in local coordinates where the original origin has the coordinates (0,0). This is to keep the metric coordinates small for convience and to maximize floating point precision (which can be quite relevant, as you observed). Therefore, by default, the transformed points from the `UTMProjector` are *not* UTM coordinates, since they were shifted to be centered around the origin.

That the UTM projector internally picks the UTM zone that fits the origin best is rather an implementation detail that should not matter as long as you stay within the "Local lanelet2 world" or use the very same projector to get back to WGS84.

If you still want the local coordinates to be identical with UTM coordinates, you have to set the `useOffset` flag to false when initializing the `UTMProjector` and pick an origin close to the middle of the UTM tile, to make sure that the correct zone is used.

Also, I would suggest to increase the precision of the `ofstream` object to at least 10 or 12 to avoid losing digits:
```c++
outputFile << std::setprecision(12) << point.x() << " " << point.y();
```

**Comment by miropipa** [comment]
Thank you for your insight. I shall do the necessary corrections to my code.
