### ISSUE TITLE
Why isn't heuristic cost calculated in ShortestPath()?

### ISSUE THREAD

**Issue by miropipa** [fzi-forschungszentrum-informatik/Lanelet2#182]
This question isn't really an issue with regards to the package itself, but general curiosity as to the choice of the path-planning algorithm used to derive the shortest path between lanelets.

From the ShortestPath.h file, I understand that the Dijkstra algorithm is used to compute and return the path with the lowest g-cost. However, there is no inclusion of the heuristic h-cost to form the f-cost used in A* algorithm, which would have theoretically reduced the computational time and cost. 

Would it be a good idea for me to modify the ShortestPath.h file in my own package to include the heuristic function of A* planner, or are there specific reasons as to why h-cost is not computed? If I were to guess, it might be because it is too computationally expensive to compute h-cost and that it might not reduce the computational time significantly if the number of nodes explored to reach the path is roughly the same.

**Comment by poggenhans** [comment]
No good reason why, rather historical reasons. Until now, no one complained about excessive computation time of shortest path.

You are probably right that the theoretical advantage of A* is not so easy to reach in practice, because for dijkstra, the whole graph and all costs are precalculated and can be queried very efficiently. For A*, the heuristic would have to be evaluated dynamically at every step, in which we would need to compute at least the bounding boxes of the two lanelets and then its geometrical distance. Therefore I would expect that A* beats Dijkstra only on very large maps or with a very carefully engineered heuristic.

**Comment by miropipa** [comment]
Truly appreciate the insight sir! 
Given the complexity of a admissible h function, Dijkstra is probably the better choice for now. Would it be possible in the near future, however, for Lanelet to use bidirectional Dijkstra instead?

**Comment by poggenhans** [comment]
If someone implements one, yes^^. We use the boost::graph implementation and it doesn't provide one, as far as I know.
