### ISSUE TITLE
lanelet2.geometry.offset() in pythonAPI

### ISSUE THREAD

**Issue by mkolodziejczyk-piap** [fzi-forschungszentrum-informatik/Lanelet2#189]
Hi, I've tried to add offset() function to python API with (I was trying to mimic toArcCoordinates() which has similar api),
```
  def("offset", lg::offset<ConstLineString2d>,
      "");
  def("offset", lg::offset<CompoundLineString2d>,
      "");
```
but but got the following error
```
TypeError: No to_python (by-value) converter found for C++ type: std::vector<Eigen::Matrix<double, 2, 1, 0, 2, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, 2, 1, 0, 2, 1> > >
```

Regards,

**Comment by soldierofhell** [comment]
Also have problem with toArcCoordinates(). This time:
```
Boost.Python.ArgumentError: Python argument types in
    lanelet2.geometry.toArcCoordinates(LineString2d, ArcCoordinates)
did not match C++ signature:
    toArcCoordinates(lanelet::CompoundLineString2d, Eigen::Matrix<double, 2, 1, 2, 2, 1>)
    toArcCoordinates(lanelet::ConstLineString2d, Eigen::Matrix<double, 2, 1, 2, 2, 1>)
```
I suppose it has something to do with ArcCoordinates class

**Comment by mkolodziejczyk-piap** [comment]
Also have problem with toArcCoordinates(). This time:
```
Boost.Python.ArgumentError: Python argument types in
    lanelet2.geometry.toArcCoordinates(LineString2d, ArcCoordinates)
did not match C++ signature:
    toArcCoordinates(lanelet::CompoundLineString2d, Eigen::Matrix<double, 2, 1, 2, 2, 1>)
    toArcCoordinates(lanelet::ConstLineString2d, Eigen::Matrix<double, 2, 1, 2, 2, 1>)
```
I suppose it has something to do with ArcCoordinates class

**Comment by poggenhans** [comment]
The reason you get this error is that you cannot use `BasicPoints2d` in the python world (at least not so simple), because it uses a nonstandard allocator (The actual type is `std::vector<BasicPoint2d, Eigen::aligned_allocator<BasicPoint2d>>`).

To make this work, you have to convert `BasicPoints2d` to `std::vector<BasicPoint2d>`. Have a look at `intersectCenterlines2d` for an example:

https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/dd447838552a860718789912917b1a7424b0c520/lanelet2_python/python_api/geometry.cpp#L368-L370

Shoot us a PR if you have it running, others will probably be interested in this too.
