### ISSUE TITLE
installing lanelet2_python

### ISSUE THREAD

**Issue by amastrobera** [fzi-forschungszentrum-informatik/Lanelet2#19]
Dear Fabian, 

I have followed the instructions in your repo (cloned both Lanelet2 and MRT repos) and did a `catking build`. All works well, but I cannot use `python -c "import lanelet2"` (ImportError: No module named lanelet2). 

What else should I do to make it available ? 

Angelo

**Comment by poggenhans** [comment]
Hi Angelo,

thank you for your interest in Lanelet2. I suppose the missing step is that you have to `source /path/to/the/workspace/devel/setup.bash`. This is a small script that is autogenerated by catkin and sets up your environment so that the packages in the workspace are correctly found by both cmake and python.
