### ISSUE TITLE
Question about exporting lanelets to binary masks

### ISSUE THREAD

**Issue by judyhuang209** [fzi-forschungszentrum-informatik/Lanelet2#196]
First of all, thank you for providing this amazing repository.
Currently I'm working on generating binary masks of roads(lanelet), something that may look like this
![image](https://user-images.githubusercontent.com/44355498/119234663-aa668780-bb61-11eb-8454-e108ea113ddd.png)

I'm using python and I extracted all the lanelets, trying to render them onto the map and then export as binary array which size is [the width of the map, the height of the map], each value is 0/1 if the point is in a lane or not. Hope I expressed my question well for English is not my native language. Could you give me some advice or is there a better way to implement this? 
Thank you!

**Comment by poggenhans** [comment]
Your approach looks ok to me.

If you are interested in rendering more complex things then just a binary map, you could search for tools designed for open street map. Since lanelet2 (ab)uses its xml format, it shouldn't be hard to render a lanelet2 map to an image with some customized style. Lanelets themselves will probably not work out of the box, but you could save their outline as a polygon and render that.

**Comment by judyhuang209** [comment]
@poggenhans Thank you for your early reply! I'll work on that.
