### ISSUE TITLE
lanelet2.geometry.findWithin2d returning more than 1 lanelet for a searched point

### ISSUE THREAD

**Issue by dinesh3367** [fzi-forschungszentrum-informatik/Lanelet2#205]
lanelet2.geometry.findWithin2d is returning more than 1 lanelet for a search point that is residing in only one lanelet. max distance argument is kept zero and still ended up getting more than 1 lanelet returned from the func call

![image](https://user-images.githubusercontent.com/31798603/125661677-3d590b93-42a5-4d4c-8e2e-3ca8067de163.png)
the above image shows one of the queried point resides in lanelet with id 1256

![image](https://user-images.githubusercontent.com/31798603/125661858-cb898670-80ce-4015-8d6b-a6a6d0bd6352.png)
the above image shows one of the lanelet with id 1258 near queried point 

the result of the lanelet2.geometry.findWithin2d function is

[id: 1258, left id: 1249, right id: 1255]
[id: 1256, left id: 1244, right id: 1246]
 
I am supposed to get lanelet id:1256 as the nearest lanelet but ended up getting lanelet id:1258 as the nearest which is wrong.

what should i have done for getting a right result ??

**Comment by dinesh3367** [comment]
to add to the above the return values from the function says the same point resides in two lanelets

[(0.0, <lanelet2.core.Lanelet object at 0x7f11ec08cb10>), (0.0, <lanelet2.core.Lanelet object at 0x7f11ec08cc90>)]

two lanelets with distance 0.0 from the queried point

**Comment by dinesh3367** [comment]
i guess i found the root cause is this because the queried point fall between these two bounding boxes ??

![image](https://user-images.githubusercontent.com/31798603/125666860-ff0654a2-d85d-492e-8bee-4342515c9e55.png)

![image](https://user-images.githubusercontent.com/31798603/125666996-39a7bc77-0845-4a0b-be63-d4969a7a5607.png)

is that the reason lanelet2.geometry.findWithin2d function says the same point resides in two lanelets

[(0.0, <lanelet2.core.Lanelet object at 0x7f11ec08cb10>), (0.0, <lanelet2.core.Lanelet object at 0x7f11ec08cc90>)]

**Comment by poggenhans** [comment]
I'm not sure if I understand completely, because I don't get where your query point is, but it seems to me that the result is correct.

`within2d` with maxDist=0 returns all lanelets for which the query point falls within the area enclosed by their right and left bound. Not the bounding box, the polygon formed by the boundaries.

**Comment by dinesh3367** [comment]
Hello, I did highlight the queried point & the returned lanelets by lanelet2.geometry.findWithin2d function with maxDist=0 

![image](https://user-images.githubusercontent.com/31798603/125737293-4695573e-fdaf-4dbd-9380-dad3161679d5.png)

As you said the query point falls within the area enclosed by their right and left bound.

**Comment by poggenhans** [comment]
So what is your problem then? It looks to me as if everything is working as expected.

If you are interested in memberships of the point instead of geometrical queries, you are probably looking for `laneletMap.lineStringLayer.findUsages(point)` which will give you the linestrings with that point and then you can use them to query the lanelets with these linestrings.

**Comment by dinesh3367** [comment]
Awesome, Thank you for your support. With your above comment i did find what i was looking for.
