### ISSUE TITLE
[Question] Tagging Traffic Light

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#21]
According to this [document](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LinestringTagging.md#traffic-lights), subtype is used to define information about traffic_light.
However, it only provides examples for simple traffic lights, like red_yellow_green. 
Are there any naming conventions for more complex traffic lights, including traffic_light with arrows, flashing lights, traffic lights for pedestrians, etc... 
e.g. how would you tag the traffic light in this [image](https://images.app.goo.gl/3APmyycqbpVd8ZVc9)?

**Comment by poggenhans** [comment]
The tagging specification in general is intentionally incomplete. it is intended that users extend it where necessary. We only defined the parts that `Lanelet2` relies on or where we think it might rely on in the near future.

For traffic_lights, we internally use a `direction` tag to model traffic lights that have arrows. This is as bad as it usually gets in Germany. But concerning your example, I am lost. You will have to come up with your own solution that reflects the habits of your country, I guess...

**Comment by mitsudome-r** [comment]
I see.

Just as comment, I thought it would be nice to have standard guideline about traffic light tagging, including the `direction` tag you mentioned. It would be troublesome if tag changes depending on the user, but I guess its difficult to have general tag to describe traffic lights in all countries...

Anyway, thank you for answering my question!

**Comment by gbiggs** [comment]
There are many, many different types of lights used around the world. For example, in New Zealand it is common to see lights dedicated to bicycles, buses or trams:

https://www.drivingtests.co.nz/media/question-images/special-traffic-signals.gif

Trams is a common one in other countries, as well. A quick search will turn up many different patterns, such as warning traffic lights about a tram approaching the intersection and lights specifically telling trams which track gets right of way *on the same light block* as lights for cars.

https://www.google.com/search?q=tram+traffic+light&hl=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj12PSH0-rhAhUiG6YKHQpwAuIQ_AUIDigB&biw=1884&bih=2033

> You will have to come up with your own solution that reflects the habits of your country, I guess...

I understand the desire not to limit where lanelets2 can be used by overspecifying, but I think it would be useful if there is structure in what is allowed. Otherwise we will find map data providers producing incompatible maps. If we were to come up with a firmer specification for traffic lights, would you be open to a PR?

**Comment by poggenhans** [comment]
> If we were to come up with a firmer specification for traffic lights, would you be open to a PR?

If you are able to find something that is good enough to fit most countrys, sure, go ahead. 

An idea would be to have something like a `direction=left/straight/right/...` tag to specify arrows. Or a `symbol` tag to cover other shapes than arrows. And a `participant:vehicle=yes/no` or `participant:bus=yes/no` to specify users that it affects. Similar to what we currently have with [Lanelets](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LaneletAndAreaTagging.md#example).
