### ISSUE TITLE
use utm coordinate in .osm file?

### ISSUE THREAD

**Issue by JackRen88** [fzi-forschungszentrum-informatik/Lanelet2#212]
Hello,everyone!
I use utm coordinate in .osm file ,as in the following format:
`  <node id="8953" visible="true" version="1" lat="0" lon="0">
    <tag k="ele" v="0.000000" />
    <tag k="local_x" v="3.964746" />
    <tag k="local_y" v="-23.600964" />
  </node>`

Do I still need to perform projection conversion when I read the .osm file,for example:
`  lanelet::Origin origin{originGps};

  lanelet::projection::UtmProjector projector(origin);
  m_map = lanelet::load(map_filename, projector, &errors);`
If not, how can I read the .osm file and use its utm coordinates directly?

**Comment by poggenhans** [comment]
The UTM projector is meant to transform WGS84 coordinates *into* UTF coordinates. Your case isn't really supported by us because we always expect the OSM file to use WGS84 coordinates.

If you really want to keep it like that, you would have to store the coordinates in the lat/lon attributes and write your own Projector inheriting from the [base Projector](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_io/include/lanelet2_io/Projection.h#L22) that simply copies the values into BasicPoints.

It's still a hack imho. Converting and storing the values as actual WGS84 coordinates would make more sense and also give you the possibility to view the map in osm editors
