### ISSUE TITLE
install lanelet2 in melodic ros environment with python3

### ISSUE THREAD

**Issue by MeiHuanshan** [fzi-forschungszentrum-informatik/Lanelet2#213]
My system is ubuntu1804 with melodic ros, the python2 is default but I want to use lanelet2 with python3. After I catkin build lanelet2 in python3 environment and use-DPYTHON_VERSION=3.6, I can "import lanelet2" in python3 but can not call "lanelet2.project", so how can I solve it?

**Comment by poggenhans** [comment]
If `import lanelet2` works, you did everything right. If there are any issues at this point, you would see them.

I suppose your problem is simply that there is no `lanelet2.project` in python. You were probably trying to access `lanelet2.projection` as it's done in the python example? https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/21e911efcde20fc281e731b5abb0167e9f00e0c2/lanelet2_examples/scripts/tutorial.py#L7
