### ISSUE TITLE
[Question] is it valid lanelet direction?

### ISSUE THREAD

**Issue by initial4** [fzi-forschungszentrum-informatik/Lanelet2#215]
Hi. I'm making a lanelet map. but I confuse lanelet direction 2, 3 case. 
Are case 2, 3 valid lanelet?  

"A lanelet consists of exactly one left and exactly one right linestring. Together they form the drivable area of the lanelet. It is required that the linestrings point into the same direction. That can mean that for two neighbouring, opposing lanelets one of them has to hold an inverted linestring as its border. When loading map data from osm, the library will do the alignment for you. "

![Lanlet_point_direction](https://user-images.githubusercontent.com/20392151/135193086-bbd21de8-6582-4b6c-a517-bf74b3821e9b.PNG)

**Comment by poggenhans** [comment]
The answer differs a bit depending on if you are referring to the representation within the library or the representation within the osm file. Within the library, all your examples are not correct:
- In 1, you would have to split the linestring in the middle into pieces so that only the part that is directly adjacent to the lane is part of the lanelet.
- In 2, you would have to invert the linestrings at 2
- In 3 and 4: one of the two lanelets would hold the inverted version (`linestring.invert())` of the shared linestring in the middle.

In the osm file, the representation is different, because there is no good way of storing the orientation of a linestring within a lanelet. For that, the parser will automatically invert linestrings as appropriate in order to form valid lanelets. So the examples 2, 3 and 4 would be corrected automatically when loading the map.

**Comment by initial4** [comment]
@poggenhans Thank you very much, This is very helpful!
