### ISSUE TITLE
[question] how to test C++ example in ROS?

### ISSUE THREAD

**Issue by haloworld-C** [fzi-forschungszentrum-informatik/Lanelet2#217]
I'm quite confused about the C++ examples in ROS, or is it nessessary to run it in ROS enviroment? I'm quiet new about Lanelet2?Could anyone kindly show me the right flow to test C++ examples?

**Comment by poggenhans** [comment]
Don't be confused by the `rosrun` statements, this is just a convenient way to run an executable within a package, wherever it might be installed.

Lanelet2 doesn't need a running ROS system (roscore) to work. It just makes use the ROS build and packaging system because it is convenient and widely used. But there is also a conan build, that has no ROS dependencies.

How you run the examples depends on how you installed lanelet2. If you got it via the ros apt package, just run them with e.g. `rosrun lanelet2_examples 01_dealing_with_lanelet_primitives `. Just don't be dissapointed if nothing seems to happen. The example executables don't output anything. If nothing failed, you can assume everything worked.

**Comment by haloworld-C** [comment]
> Don't be confused by the `rosrun` statements, this is just a convenient way to run an executable within a package, wherever it might be installed.
> 
> Lanelet2 doesn't need a running ROS system (roscore) to work. It just makes use the ROS build and packaging system because it is convenient and widely used. But there is also a conan build, that has no ROS dependencies.
> 
> How you run the examples depends on how you installed lanelet2. If you got it via the ros apt package, just run them with e.g. `rosrun lanelet2_examples 01_dealing_with_lanelet_primitives `. Just don't be dissapointed if nothing seems to happen. The example executables don't output anything. If nothing failed, you can assume everything worked.
