### ISSUE TITLE
Querying for lanelet in only one direction

### ISSUE THREAD

**Issue by ajay1606** [fzi-forschungszentrum-informatik/Lanelet2#225]
Hello,
Thanks for the very useful repository and along with tutorial. 
Currently, am looking for extracting the nearest lanelet to my GPS location. Referring to [example](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_examples/src/03_lanelet_map/main.cpp), in the repository I succeeded to retreive lanelets nearest to GPS location. 
This Line in the example code :  `Lanelets inRegion = laneletMap.laneletLayer.search(BoundingBox2d(BasicPoint2d(0, 0), BasicPoint2d(10, 10)));` returns all the nearest lanelet, But i am looking for retreiving lanelets only in the vehicle driving direction. Is there any way that i can filter out opposite direction lanelet in my querry ?

![image](https://user-images.githubusercontent.com/29722843/144369663-da0230e9-61b3-498e-a84b-ff55b1ddb330.png)

Any response is appreciated. 

Regards,
Ajay

**Comment by poggenhans** [comment]
Queries on a lanelet map are always purely geometrical, since the lanelet map doesn't hold any information about lanelet relations.

To get information about routes an lanelets nearby, you have to use the routing graph, determine a route for your vehicle with it, get the submap for that route and query that. Roughly like this: `routingGraph->getRoute(from, to)->laneletSubmap().laneletLayer.search(...)`.

**Comment by ajay1606** [comment]
@poggenhans Thanks for your quick response.
