### ISSUE TITLE
No module named 'lanelet2.matching'

### ISSUE THREAD

**Issue by Coding-Monki** [fzi-forschungszentrum-informatik/Lanelet2#226]
Hello, I'm trying to import the lanelet2.matching module in Python using Ubuntu 20.04 and ROS noetic.
Unfortunately this gives me a ModuleNotFoundError. Besides this module, all other lanelet2 modules work flawlessly.

**Comment by m-naumann** [comment]
That's strange, since https://build.ros.org/job/Ndev__lanelet2__ubuntu_focal_amd64/18/testReport/test_lanelet2_matching/MatchingApiTestCase/test_matching/ (corresponding to https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_python/test/test_lanelet2_matching.py#L57) passes. 
Can you run the tests locally?

**Comment by Coding-Monki** [comment]
Thank you for the fast answer.
When I run the test locally I get the following error output:
`Traceback (most recent call last):
  File "/home/user/lanelet_ws/src/Lanelet2/lanelet2_python/test/test_lanelet2_matching.py", line 5, in <module>
    from lanelet2.matching import Pose2d, getDeterministicMatches, getProbabilisticMatches, Object2d, ObjectWithCovariance2d, PositionCovariance2d, removeNonRuleCompliantMatches
ModuleNotFoundError: No module named 'lanelet2.matching'`

**Comment by poggenhans** [comment]
The answer is quite simple: There hasn't been a new release since we added `lanelet2_matching`. To use it, you have to build it from source.

The ndev build on the ros build farm just *tests* the current master branch, the release jobs are separate.

**Comment by tuschla** [comment]
When will there be a new release of lanelet2 for the ROS depository containing lanelet2_matching?
