### ISSUE TITLE
failed to compile lanelet from source because of cmake not finding "/include"

### ISSUE THREAD

**Issue by Coding-Monki** [fzi-forschungszentrum-informatik/Lanelet2#227]
I've been trying to compile the lanelet2 package from source on an Ubuntu 20.04 machine with ROS1 noetic installed.
cmake throws the following error:
```
Errors     << lanelet2_core:cmake /home/user/lanelet_ws/logs/lanelet2_core/build.cmake.000.log
CMake Error in CMakeLists.txt:
  Imported target "lanelet2_core::auto_deps_export" includes non-existent
  path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
I found someone trying to compile boost, who was also experiencing the same issue, maybe its related:
https://gitlab.kitware.com/cmake/cmake/-/issues/19841

**Comment by poggenhans** [comment]
Phew, thats hard to say. Since it builds within docker 20.04 containers with noetic installed and it builds in the ROS buildfarm for noetic, it must be something related to your system.

What is happening in the background is that all dependencies of `lanelet2_core` are aggregated into this `auto_deps_export` target. That means if *some* library that you have installed and that lanelet2 uses (like boost), sets a nonexistent include path, you can get this error.

**Comment by Coding-Monki** [comment]
Maybe you could please give me a hint how to get rid of those unexistent paths

**Comment by poggenhans** [comment]
Well one thing you can do is to manually run `cmake` with the `--trace-expand` flag on the `CMakeLists.txt` of `lanelet2_core`. That will give you the complete line-by-line output of what cmake does. That should give you all information about how that include path found its way into the `auto_deps_export` target.
