### ISSUE TITLE
Release lanelet2 to `rolling` distro again

### ISSUE THREAD

**Issue by wep21** [fzi-forschungszentrum-informatik/Lanelet2#230]
`lanelet2` is once removed from `rolling`. in the sync below.
https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2021-11-02/22963
This is caused by `ament_cmake` update and `mrt_cmake_modules`.
https://github.com/KIT-MRT/mrt_cmake_modules/pull/28
https://github.com/ament/ament_cmake/pull/355
I fixed the this issue and `mrt_cmake_module` is prepared for new release,
so `lanelet2` is also ready to release for rolling again after https://github.com/ros/rosdistro/pull/31421.

**Comment by wep21** [comment]
@poggenhans Could you prepare to release to `rolling` again?
@nuclearsandwich Is there any additional process to release a package which is removed once?

**Comment by poggenhans** [comment]
There is nothing to do on our side. Lanelet2 is still in the [rosdistro file](https://github.com/ros/rosdistro/blob/14dd2b2f0671d3aa401a194ff09d34a378960692/rolling/distribution.yaml#L1338). But since `mrt_cmake_modules` does currently not build on `rolling`, `lanelet2` cannot be built either. And so it was apparently removed in the latest sync.

If that is fixed, lanelet2 should automatically be part of the next release too.

**Comment by wep21** [comment]
@poggenhans I see. Thanks!
