### ISSUE TITLE
How to get the global adjacency matrix of routing graph?

### ISSUE THREAD

**Issue by RomainLITUD** [fzi-forschungszentrum-informatik/Lanelet2#241]
Hi, 

After building a routingGraph from lanletmaps, we can search following/previous/left/right lanelets of a target lanelet. But can we directly get the adjacency marix of the routingGraph? I want to do chain decompostion of a road network but don't know how to get the directed adjacency matrix? Or anything similar? Both C++ or python are ok.

Thank you!

**Comment by poggenhans** [comment]
The adjacency Matrix is an implementation detail that we are not exposing to the outside so that we can make changes under the hood in the future without affecting users (as we have already done in the past). Actually it's not even a matrix, rather a list.

I'd recommend you build your own adjacency matrix according to you needs, either by walking though the lanelets in your map and using the following/previous/left/right/adjacent accessors to get the edges or by using the `exportGraphML` and `exportGraphviz` exports and analyse that.
