### ISSUE TITLE
how to make lanelet map with shape file?

### ISSUE THREAD

**Issue by ZhangHongjuan** [fzi-forschungszentrum-informatik/Lanelet2#25]
Hi, Thanks for your work. I have a shape file of a driving road. I want to make a lanelet map with this shape file. Could you please tell me how? Thanks a lot.

**Comment by poggenhans** [comment]
Sorry I have no idea what you mean with a "road shape file". Can you be more specific on the information you require assuming you already read through our documentation?

**Comment by ZhangHongjuan** [comment]
Hi, yes, I have gps points of both left and right boundaries of road

**Comment by poggenhans** [comment]
Ok, that still does not help me to find out what you want to achieve. The shape of the road will most likely be not sufficient, because lanelet2 requires lanes. 

You could interpret your road as a single lane and create one single lanelet from it. For that you can transform your GPS points into a local coordinate system using e.g. the `SphericalMercatorProjector` from `lanelet_io`, create a `LineString3d` from the left and right bound and then a `Lanelet` from these bounds.

**Comment by ZhangHongjuan** [comment]
Thanks for your reply. I really appreciate it. Actually my datasets includes many lanes, we required that data in a highway road with variable numbers of lanes and complex intersections. There are more than 400000 gps points in our file, and it's very diffcult to make a lanelet style map by JOSM manully.  I am wondering, is the method you mentioned above possible to handle our case? Or it's only for a single lane?

**Comment by poggenhans** [comment]
> I am wondering, is the method you mentioned above possible to handle our case?

You should be able to implement some converter that works based on this method. The approach would be to create one lanelet per lane in your database, add that to a `LaneletMap` object and then write this LaneletMap to the OSM-XML-format.

You should just make sure neighbouring laneles actually share the exactly same boundary, otherwise Lanelet2 will not be able to identify that they are neighbours.

**Comment by ouyangandy** [comment]
> Hi, Thanks for your work. I have a shape file of a driving road. I want to make a lanelet map with this shape file. Could you please tell me how? Thanks a lot.
您好，大佬，可以加您的联系方式吗？关于地图这块想跟您请教一些问题。包括这个项目该怎么使用。非常感谢大佬。
