### ISSUE TITLE
Unable to import files -> ROS2

### ISSUE THREAD

**Issue by REGATTE** [fzi-forschungszentrum-informatik/Lanelet2#257]
Hi,
I'm trying to interface lanelet2 and publish various messages via ROS2 humble on Ubuntu 22.04

Installed lanelet2 via ``` sudo apt install ros-humble-lanelet2```, and it installed without any issues,

I've even added lanelet2_core and others into the CMakeLists.txt as exec_depend packages.

I've been trying to import *BasicRegulatoryElements.h*, by `#include "lanelet2_core/primitives/BasicRegulatoryElements.h", but get the error of 

```
no such file or directory
```

I've looked through the lanelet2_examples to try for any changes, and nothing worked for me.

Attached is the link to the git folder

[LINK](https://github.com/Avyana-Tech/map.core/tree/main/lanelet2_common_extensions)

**Comment by poggenhans** [comment]
Finally someone who also includes some code together with his issue 👍 .

I don't think your problem has anything to do with ROS2 (or even lanelet2). It rather looks to me as if your `CMakeLists.txt` is incorrect. You are mixing `ament_cmake` and `ament_cmake_auto`.

I'm not so deep into `ament_cmake_auto`, but I think using `ament_auto_add_library` requires a calling `ament_auto_find_build_dependencies` first. But since you are also explicitly using `find_package(lanelet2_core)`, you could also link manually: `target_link_libraries(lanelet2_common_extensions_lib lanelet2_core)`.

**Comment by REGATTE** [comment]
Hi,

So since I've explicitly mentioned find_package() and using ament_cmake_auto, I don't need to link them manually. I've actually forgotten to write a CMake argument

```
ament_auto_find_build_dependencies()
```

Now this starts giving me a whole different set of errors, related to ROS2. But since the main reason for opening this issue, is done I'm closing this. 

Thanks for the help! 💫

Also if you want to check the changes, its on the same link above.
