### ISSUE TITLE
US/California Traffic Rules/Sample file available?

### ISSUE THREAD

**Issue by PhCroAtlatec** [fzi-forschungszentrum-informatik/Lanelet2#263]
We are producing lanelet2 maps and want to encode speed limits as regulatory elements. However, the repository only contains German traffic rules and associating lanelets with "de274-xxx" `sign_type` does not seem appropriate. 

Is there any implementation of traffic rules for the U.S. (California to be more specific)? Is there any sample file with speedlimits for this region?

Thanks!

**Comment by poggenhans** [comment]
The US (and all other) traffic rules are waiting for someone to implement them 😉.

I know that the [interaction dataset](https://interaction-dataset.com/) contains lanelet2 maps from the US/California, among others. But I don't know how traffic signs are represented there, if at all.

**Comment by m-naumann** [comment]
That's right. For the interaction dataset, we added the all-way-stop regulatory element and the stylesheet to josm for mapping of the US roadsigns (see https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LinestringTagging.md#traffic-signs), but not for the speed limits, we simply went with

```xml
<tag k="sign_type" v="15mph" />
```

as described here: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/RegulatoryElementTagging.md#speed-limit.

This is indeed not too nice, but works out of the box. 

Since the German style of naming signs uniquely including the numbers on them (i.e. one sign id per speed limit) is not used in the US (they are all simply referred to as `R2-1`), maybe adding the key `speed_limit` and requiring it for non-German signs would be one possible solution. Or one could "invent" the `usR2-1-xxx`(xxx in mph) style, and add it to https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/cc815028e9faf913824b2a4aff5d111d153213ba/lanelet2_traffic_rules/src/GermanTrafficRules.cpp#L22 which would be easier to implement/cause less changes.

What do you think @PhCroAtlatec @poggenhans @immel-f ?

**Comment by immel-f** [comment]
I like the idea, but I think if we "invent" a `usR2-1-xxx`  style we should move it to a separate file like `USATrafficRules.cpp` to not confuse people with the inconsistent naming of files.

**Comment by PhCroAtlatec** [comment]
My personal suggestion would be to allow  `<tag k="sign_value" v="XXX" />` on road signs. There are many other cases where road signs cannot be accurately represented with just a type. Appending the value can work as @m-naumann  suggested, but in some other cases, where "value" could represent some text written on the sign, this won't be a nice solution.

Having traffic rules for USA (or even more specifically for California) would definitely be nice.

For now, we can just go with `<tag k="sign_type" v="15mph" />`, though! Thanks a lot for this hint!
