### ISSUE TITLE
lanelet2.io.load() crashes on a map cropped from JOSM

### ISSUE THREAD

**Issue by amastrobera** [fzi-forschungszentrum-informatik/Lanelet2#29]
Dear Lanelet2 guys, 

I tried to crop a piece of map from JOSM, saved it as osm, and tried to open it with `lanelet2.io.load(<osm_map>, <origin_lat_lng_of_its_center>)` but for this error: 

```
RuntimeError: Errors ocurred while parsing Lanelet Map:
	- Error reading primitive with id 74660 from file: Relation has nonexistent member 550284583
 .... and many more
```

Apparently some relations are chopped off the crop I did. Should I not save maps that way ? if not, what is the best way to use a piece of JOSM map ?

**Comment by poggenhans** [comment]
From afar it's hard to say what exactly is missing. If you delete primitives in JOSM, the relations that referred to them are still there, even if they have zero members. If you don't delete them as well, you end up with Lanelets without borders. And then the parser of Lanelet2 complains about that. You could search for relations with zero members in JOSM and delete them.

You could also try to load them with `loadRobust` which loads the remaining map despite errors and then write the remaining map again. All the things that could not be loaded will be lost, but if these are just empty relations that shouldn't matter.

**Comment by amastrobera** [comment]
I can send you the file. Can you try uploading it with 
```
projector = lanelet2.projection.UtmProjector(
                lanelet2.io.Origin(51.49,-0.04))
lmap, err_list = lanelet2.io.loadRobust(osm_path, projector) 
```
You will see that `len([l for l in lmap.laneletLayer]) == 0` and that `err_list` is quite large. 

[Autonomoustuff.zip](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/files/3216492/Autonomoustuff.zip)

**Comment by amastrobera** [comment]
@poggenhans  did you manage to open it ?

**Comment by poggenhans** [comment]
Here is what I found:
- You are using a wrong origin. It has to be in the same UTM tile as the map data, otherwise the projector will complain (there are a couple of `Error parsing primitive xxxxx: Longitude -121.xxx more than 60d from center of UTM zone 30` in the error list)
- Since this is a "normal" osm file and not a lanelet map, there are obviously no lanelets in the map. But if you check the linestring layer, you will see that it actually loaded the ways in the map as linestrings
- There indeed seems to be something wrong with the relations. They reference things that are not in the map file. JOSM itself shows these as "incomplete". But lanelet2 does not load these relations anyways because they have no meaning as long as they are not tagged as "area", "lanelet" or "regulatory_element". Therefore these errors do not matter.
