### ISSUE TITLE
Lanelet2 pip wheel incompatible with `GLIBC_2.28`

### ISSUE THREAD

**Issue by m-naumann** [fzi-forschungszentrum-informatik/Lanelet2#292]
The pypi wheel currently requires `GLIBC_2.29` and `auditwheel` is not able to "repair" it to `2_28` if changed here:
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/11e83fdd208e06fe1131cbf5aeaea7586a3d0a99/.github/workflows/cd.yaml#L73

Workable solution is a conan build as in https://github.com/jdrudolph/Lanelet2/blob/bb64b1a118c428c759cf86d7a48d58a5466fe4cc/Dockerfile_conan_cp38

**Comment by poggenhans** [comment]
And what exactly is the issue?

**Comment by reiniscimurs** [comment]
Hi,

The issue here is that current pip wheel is hard-coded to the glibc2.31 version. That means that if your system has an earlier version of glibc, the pip installation will not work (because of missing pip tags). Simply downloading and renaming the wheel file will allow for installation, but you would still require at least glibc2.29 version to run lanelet2. So if your system has glibc2.28 or earlier, the current wheel does not work. Either it is required to update glibc version or a workaround it is a conan build.

**Comment by poggenhans** [comment]
What I meant was: What is the original issue. I know we don't support older libc versions (and others) but which linux distributions are actually affected by this?

**Comment by reiniscimurs** [comment]
Hi,

The affected linux distributions that I am definitely aware are RedHat Linux versions 8.7 and below.
https://distrowatch.com/table.php?distribution=redhat

According to distrowatch, Ubuntu versions below 18.10 would be affected as well.
https://distrowatch.com/table.php?distribution=ubuntu
