### ISSUE TITLE
python io.load memory usage issue

### ISSUE THREAD

**Issue by veekxt** [fzi-forschungszentrum-informatik/Lanelet2#373]
I found that laneletMap occupies memory for at least one object. In the example below, it doesn't occupy memory for 8 objects, which seems normal. However, it will still occupy memory for one object, which is hard to accept, especially since my OSM file is large. How can I clear all memory usage?

```py
import lanelet2
import time

def build_graph():
    j = lanelet2.projection.UtmProjector(lanelet2.io.Origin(49.0, 8.4))
    lanelet_map = lanelet2.io.load("files/t2.osm", j)
    del lanelet_map # del also doest work
    return None

if __name__ == "__main__":
    for i in range(8):
        build_graph()
    time.sleep(100)
```

And, a 70MB OSM file that occupies about 600MB of memory. What are the methods to reduce memory usage as much as possible?

**Comment by immel-f** [comment]
Thanks for the code example, I could also confirm that the memory of one map object remains occupied even when they are deallocated. @poggenhans Do you have an idea what could cause this? Code example with print statements for memory: 

```py
import lanelet2
import time
import psutil
process = psutil.Process()

def build_graph():
    j = lanelet2.projection.UtmProjector(lanelet2.io.Origin(49.0, 8.4))
    lanelet_map = lanelet2.io.load("mapping_example.osm", j)

    print("Memory in loop: " + str(process.memory_info().rss / (1024*1024)) + " MB")  # in megabytes 
    
    #return lanelet_map


print("Memory at start: " + str(process.memory_info().rss / (1024*1024)) + " MB")  # in megabytes
maps = []
for i in range(8):
    maps.append(build_graph())
    print("Memory after loop: " + str(process.memory_info().rss / (1024*1024)) + " MB")  # in megabytes
time.sleep(1)
```

Regarding the fact that the loaded map occupies more space than the OSM file: Generally it is hard to deduce that from memory usage of a process, as loaded shared libaries etc. are also included in that number. However it is expected that the loaded map is larger, as loading the map is not just creating a large string with the xml file in it, but creating all of the map element objects, maps for id lookup etc.

**Comment by poggenhans** [comment]
This has nothing to do with lanelet2, its normal python behavior. Firstly, python is not required to actually delete objects if they are no longer used. Objects with complicated reference cycles are only cleaned after a garbage collection run. Secondly, even if python removes objects, it doesn't mean that memory is actually freed. Python or the libc allocator might decide to keep it reserved for a while just in case its needed again. I'm not sure if there is a way to tell python to shrink the process to the minimal size possible. End even if, due to memory fragmentation, that value might still be larger than before.

If size of the map is an issue, clean it. Remove points that do not contribute to shape of a line, remove lanelets that you are not interested in, etc.

**Comment by veekxt** [comment]
Ok, thanks for your answer.
