### ISSUE TITLE
[Feature] LaneLet2 python on Windows

### ISSUE THREAD

**Issue by Jazzinghen** [fzi-forschungszentrum-informatik/Lanelet2#38]
I would like to be able to handle LaneLet2 files in a project on windows but at the moment there is no way to use the Python submodule on Windows (or on Linux without ROS) due to its ROS dependencies.
Is there any way to use it as a separate package instead of part of the entire project?

**Comment by poggenhans** [comment]
We are currently working on `conan` support (see the `conan_support` branch). That would rid us of the ROS/catkin dependency. However, currently that does not work with the python bindings. It is also possible to build `Lanelet2` purely without a ROS installation, as long as `catkin` is available. But that could be built and installed from source.

Regarding Windows: We are not developing for Windows, since we would be unable to test it in a CI environment and we are not using it ourselves. Even if we fix the catkin requirement, there might be issues in CMake due to incompatible flags and within Lanelet2 due to wrong filesystem paths.

These should be easy to fix, but we cannot guarantee that we wont introduce new issues in the future, since we don't test for them.

**Comment by FerGarrido** [comment]
Hello again.

First of all, thank you for your work.
I have tried to build the lib from windows folowing the instructions in the documentation. Howerver, it does not work. I have the following error when executing the following code:
`conan create . lanelet2/stable --build=missing`
```
X:\Lanelet2>conan install lanelet2/0.0.0@lanelet2/stable --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

lanelet2/0.0.0@lanelet2/stable: Not found in local cache, looking in remotes...
lanelet2/0.0.0@lanelet2/stable: Trying with 'conancenter'...
lanelet2/0.0.0@lanelet2/stable: Trying with 'conan-center'...
lanelet2/0.0.0@lanelet2/stable: Trying with 'bincrafters'...
ERROR: Permission denied for user: 'fgarrid2'. [Remote: bincrafters]
```

**Comment by poggenhans** [comment]
I'm not really sure if you problem is related to this issue, to me it looks rather like a conan specific problem.

The command line output (`conan install`) is not consistent with your command (`conan create`), so probably it is related to this. If you are unsure, have look at how we do it in our (linux-based) CI:
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/1e659dab3cade16ab8aebc62af1f44126ed525a7/.gitlab-ci.yml#L78-L80

If your problem persists, please open a new issue with more details to keep things separate.

Just to warn you: Even if this problem is solved, there is little hope this project will work on Windows out of the box. We are not supporting it and as far as I know it has never been tested on this platform, so expect to run into all the usual Windows-specific problems.
