### ISSUE TITLE
[Question] Why prohibit diverging and merging at the same time? 

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#51]
When I tried to create a routing graph with a lanelet that diverge and merge at the same time, it gave me following error:
```
Could not determine relationship between lanelets following lanelet 2. Lanelets that are diverging and merging at the same time are not permitted."
```

Are there any particular reason you prohibit this? It seems like it is using relation just for assigning costs, but it is assigning the same cost for successor, merging, and diverging anyways, so why not add new RelationType::DivergingAndMerging with same cost?

**Comment by poggenhans** [comment]
That we don't allow merging and diverging at the same time is not so much a technical limitation (you are right, we could simply add this relation). We rather decided to disallow it because we thought allowing it could result in strange side-effects. 

To trigger this assertion, you would need to have a lanelet that forms a loop and other lanelets that connect to this loop. That means that vehicles that are on the loop are at the same time leaving and approaching and all implementations using lanelet2 would have to consider that. And so we concluded that allowing this case would most likely cause more trouble than prohibiting it. Also it is almost always a result of a mapping error. So far we could only come up with unrealistic and strange-looking examples where such a case is actually wanted.

If you really want that to work, you could simply split the looping lanelet in two.

**Comment by mitsudome-r** [comment]
Thank you for your answer.

> That means that vehicles that are on the loop are at the same time leaving and approaching and all implementations using lanelet2 would have to consider that.

I understand that you don't want to handle such strange situation, but I got this error where there is no loop. The example is shown in the attached image where two lanelets are merging and two lanelets are branching at same contact points. I think this situation is not so strange in real situation. Of course we can add short lanelet to split the merging point and branching point, but I thought it was rather strange to add such small lanelet just to avoid the error from routing graph. 
![Screenshot from 2019-09-09 14-09-35](https://user-images.githubusercontent.com/43976834/64504874-ad2d3480-d30c-11e9-9cfe-cbfcbf39fae7.png)

**Comment by poggenhans** [comment]
Ah, thanks for the explanation. I was not aware that this triggers the assert as well. 

We will have to think of something there. I would rather avoid having to introduce an extra relation type because it existance is easily forgotten...

**Comment by poggenhans** [comment]
With the newest update, we removed the "diverging" and "merging" relations completely. Now there is only "successor". With that, your assert should be gone now.
