### ISSUE TITLE
How to convert from ArcCoordinates back to x, y?

### ISSUE THREAD

**Issue by autonomobil** [fzi-forschungszentrum-informatik/Lanelet2#52]
Say I have a centerline of a lanelet and the position of an object on this lanelet. Now I want to predict the movement of the object by following the lanelet. I can assume a linear motion model along the centerline of the lanelet with a specific offset/distance to centerline.

```
//Point3d posObj;
//Lanelet lanelet;

ConstHybridLineString3d centerline = utils::toHybrid(lanelet.centerline());
ArcCoordinates arcCoordinates = geometry::toArcCoordinates(utils::to2D(centerline), utils::to2D(posObj));
```

The arcCoordinates length and distance are the centerline coordinates which is something like Frenet-coordinates, correct? The distance is the perpendicular component and the length is the distance along the centerline, correct?
I can get the current distance and length of the object on the centerline with:
```
double s_start = arcCoordinates.length;       
double t_start = arcCoordinates.distance;
```

I want to predict the movement by doing something like s = s_start + v*dt. 

So how can I transform back from centerline-coordinates(length **s**, distance **t**) to x,y-coordinates?
Do I use **interpolatedPointAtDistance**?

**Comment by poggenhans** [comment]
Yes, they are frenet-coordinates, but for the special case of a piecewise-linear linestring, not of a curve. Because of that, there is no unambiguous way of getting back from arc coordinates to metric ones. This happens whenever `s_start` falls on the endpoint of a segment.

`interpolatedPointAtDistance` only gives you the x,y-coordinates of a point on the line string at the given distance. You could use that or `closestPointAtDistance` to find the respective segment and then compute the point you want using `t_start` as offset to the point on the segment. But as I said: That will give you strange jumps whenever the vehicle passes a segment endpoint.

We are currently working on publishing a function that offsets the whole centerline by a fixed distance (ETA next week). That might be a more appropriate way of predicting the movement with a fixed offset to the centerline.
