### ISSUE TITLE
Release to ROS Build Farm

### ISSUE THREAD

**Issue by JWhitleyWork** [fzi-forschungszentrum-informatik/Lanelet2#53]
Any plans to release this to the build farm? We would love to not have to build this as a dependency.

**Comment by poggenhans** [comment]
You are talking about the ROS build farm? No plans, but rather because we have no experience with it, not because we don't want to.

Also I am not sure if ROS is already admitting C++14. Last time I checked at least C++11 support was required. And mrt_cmake_modules might be a problem. We could release it as well but I would rather avoid the extra work since it is only required for building.

**Comment by JWhitleyAStuff** [comment]
@poggenhans - Sorry I haven't responded to this lately. Yes, I was talking about the ROS build farm. They are accepting C++14 code, but only for ROS Melodic and above (which is really what we care about). Since `mrt_cmake_modules` is a pure CMake thing, it also shouldn't be a problem to release it and doing so is very easy. It can then be added as a `<build_depend>` since it is required at build-time but not compile-time. I would be happy to walk through the release process with you  on either repo. Please email me at jwhitley@autonomoustuff.com and we can set something up.

**Comment by poggenhans** [comment]
ros/rosdistro#24060

**Comment by JWhitleyWork** [comment]
Awesome! Thanks!
