### ISSUE TITLE
How to delete a point by ID

### ISSUE THREAD

**Issue by amastrobera** [fzi-forschungszentrum-informatik/Lanelet2#57]
Dear Lanelet guys, 

I use this code to get rid of points created by mistake or make changes in the Linestring3D of a Lanelet. It seems **the API lets me remove points from a LineString but not completed delete the point from the Map. Can this be changed ? ** 

```
import lanelet2
import lanelet2.core as lncore

# create one lanelet with two borders with points 1,2,3,4
lb1 = lncore.LineString3d(lncore.getId(),
                [lncore.Point3d(lncore.getId(), 4, 0, 0), lncore.Point3d(lncore.getId(), 4, 2, 0),
                 lncore.Point3d(lncore.getId(), 3, 3, 1), lncore.Point3d(lncore.getId(), 3, 4, 1)])
rb1 = lncore.LineString3d(lncore.getId(),
                [lncore.Point3d(lncore.getId(), 6, 0, 0), lncore.Point3d(lncore.getId(), 6, 2, 0),
                 lncore.Point3d(lncore.getId(), 5, 3, 1), lncore.Point3d(lncore.getId(), 5, 4, 1)])
llet1 = lncore.Lanelet(lncore.getId(), lb1, rb1)

# add to map
lmap = lncore.LaneletMap()
lmap.add(llet1)

# remove the point 1 from each border
for llet in lmap.laneletLayer:
    del llet.rightBorder[0]
    del llet.leftBorder[0]

# print out the points of the borders (they are updated, and only contain points 2,3,4
for llet in lmap.laneletLayer:
    print ("right border: %s" % [(p.id, p.x, p.y) for p in llet.rightBorder])
    print ("left border: %s" % [(p.id, p.x, p.y) for p in llet.leftBorder])

# print all points in the map: the deleted points are still there
for p in lmap.pointLayer:
    print ("point %d (%.2f,%.2f)" % (p.id, p.x, p.y) )

# finally I want to delete the individual points ... but this won't work function "__delattr__" is not implemented
#for p in lmap.pointLayer:
#    del p 
```

**Comment by poggenhans** [comment]
Its not a limitiation of the python interface. The C++ interface does not allow this as well.

The reason is that a LaneletMap is designed such that it always self-contained. It always contains all primitives that are used by other primitives in the map. Offering a delete function would be misleading, since it would not actually not delete the point if it was still in use by other LineStrings.

We might think about having something like `removeIfUnused` in the future, however. But since you usually want to have a map that does not contain any unneeded objects at all, the best approach is to simply create a new map with the primitives you actually need (e.g. with `createMapFromLanelets`).

**Comment by amastrobera** [comment]
Thanks for the explanation. Yes `removeIfUnused` would be good. For now I found another way around to achieve what I wanted.

**Comment by dinesh3367** [comment]
could you post the solution you had found for this issue ??

**Comment by amastrobera** [comment]
if you are talking to me, my solution was simply to created `lineString` or `lanelet` elements in memory, instead of immediately putting them in the map. each time I had to edit a point of those linestrings I edited in memory. when the lines were all correct (no redundant points) I would finally add them in the map.

**Comment by dinesh3367** [comment]
Thanks @amastrobera we followed a similar approach and found map editing possible with a similar approach like yours. Thanks for that heads up
