### ISSUE TITLE
[Question] Why is possiblePaths() not outputting paths with lane changes and merging lanes?

### ISSUE THREAD

**Issue by autonomobil** [fzi-forschungszentrum-informatik/Lanelet2#65]
I have the following situation: An object is matched to a lanelet and from its position all possible paths with lane changes are generated. Lane changes in the path are then detected and processed. 

It looks something like this (yellow are possible paths):
![rviz_screenshot_2019_12_16-17_19_40](https://user-images.githubusercontent.com/31781343/70924203-706a8b00-2029-11ea-9731-c46ddf9ae4a7.png)

If I set the minimum length in the `possiblePaths`-function to something like 100m, the path with lane change isn't even in the output, what's the problem there? Function call looks something like this:

`routingGraph->possiblePaths(currentLanelet, 100.0, 0, true);`

So to get the path with the lane change I call the function with:

`routingGraph->possiblePaths(currentLanelet, 0.1, 0, true);`

As you can see the path with the lane change ends where it would cross/merge with the "original" path, is there something implemented that prohibits the path with lane change to extend further? Why does it stop there? There no more lanelets in the path-object. Probably the **0.1m** allow for only-2-lanelet-paths, so after a lane change more than 0.1m are covered and it stops.

So the question still remains, why isn't the possiblePaths-function not outputting the path with the lanechange if the min. distance is set to a high value?

**Comment by poggenhans** [comment]
Well as the documentation says: 

> Returns possible paths that are at least as long as specified in 'minRoutingCost'. If a lanelet can be reached using different paths, only the one is included that requires the least number of lane changes and has minimum routing costs

I suppose that with your 0.1 example, the minimum cost is just small enough to allow the lane change but nothing more. So its successors are not added to the path.

For your call with cost 100, the route with the lane change would use the same lanelets as the route without lane change, so it is not included in the result.

The reason why the function is implemented this way is because it is hard to define what a sane "possiblePath" is in the presence of lane changes. From the perspective of the graph for two lanelets A and B that are reachable through lane changes, the sequence ABABABA... is a perfectly valid possiblePath. But it is usually not what users want. So to exclude paths that are composed of excessive numbers of lane changes, every lanelet is allowed to be reached only through one path.

**Comment by autonomobil** [comment]
Okay that makes sense. 

The only thing is that the path with the lane change doesn't use all the same lanelets. For example if you want the path to lanelet -885624, you have two options:

1. You could go via the current lanelet -> -885655 -> -885624, 
2. You could also go via current lanelet -> lane change to right -> -885623 -> -885624.

(-885623 and -885655 are merging)

Shouldn't this be covered by possiblePaths()? Of course after -885624 they would share the same lanelets but it would be two different paths to get there.

**Comment by poggenhans** [comment]
This decision is never explicitly available when building the possible path. The search is implemented in terms of a dijkstra graph search. In these searches, it is simply not possible to visit a vertex a second time with suboptimal costs.

PossiblePaths is supposed to answer the question "where can an object be after it moved X meters and what path will it most likely take?". If you are instead asking "what lanelets can an object use within the next X meters", the reachableSet function might be better, because it does not care how many paths there are to reach a certain lanelet.

**Comment by poggenhans** [comment]
Btw. we now have the function `RoutingGraph::forEachSuccessor` which you can use to search the graph in a custom way. However, It visits every lanelet only once, so you might need to add missing connections in a second pass if you need them.

**Comment by autonomobil** [comment]
Perfect! Thank you very much

**Comment by autonomobil** [comment]
What do you mean with a second pass? How would you do it?
