### ISSUE TITLE
[Question] What is the best flow for performing runtime geometry updates?

### ISSUE THREAD

**Issue by msmcconnell** [fzi-forschungszentrum-informatik/Lanelet2#66]
What is the recommended way of performing updates to the geometry of map lanelets at runtime. If a vehicle senses a construction zone and there is a shifted lane. How should the map be updated to reflect that to minimize the re-computation of search trees, centerlines, etc.? What functions are important to call to ensure the map remains valid?

**Comment by poggenhans** [comment]
Updating existing maps is still a todo, sorry. It is doable to implement it but until now nobody needed that feature. it's also not trivial to implement because all the elements in the map that use the modified primitive would have to be updated recursively as well.

The only approach currently available is to create a completely new map that contains all the elements from the old map you are interested in.

**Comment by msmcconnell** [comment]
@poggenhans Thanks for clarifying that. I suspected that might be the case. Is this something you plan to work on at all in the near future or is it a long way off?

**Comment by poggenhans** [comment]
Hm, it might be something we might squeeze into our lanelet2_ros release. But right now I cannot give you a good ETA. It might be two months, but it might very well be more. I'll keep this issue open as a "friendly reminder".

**Comment by autonomobil** [comment]
Side question, when are you planning to release lanelet2_ros?

**Comment by poggenhans** [comment]
Probably March or April.
