### ISSUE TITLE
[Question] Using maps in multiple nodes

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#7]
Since there is rosdoc.yaml in the repository, I assume Lanelet2 can be used for ROS systems. 
If we are to use the map information in multiple ros nodes, how should the map be shared? 
I don't see any ROS messages defined so are you using other framework.  
If you have any experience on using map across multiple nodes, could you tell me how you did it?
Thank you in advance.

**Comment by poggenhans** [comment]
Hey, thanks for your interest in Lanelet2 - and sorry for the late reply!

Lanelet2 uses the ROS ecosystem (mainly Catkin) for building and testing because we also use it internally for our software. Apart from that, Lanelet2 itself is independent of ROS.

However, we are currently working on packages that make it easier to use within ROS (messages, interfaces, Rviz plugins and so on) and will release them later this year.

**Comment by mitsudome-r** [comment]
@poggenhans 
Thank you for your reply!
I'll wait for the release then.

**Comment by fkthi** [comment]
Hello,
is there any news on the packages you planned to release?
Thanks

**Comment by poggenhans** [comment]
Hi @fkthi, we offer a work-in-progress version here: https://github.com/coincar-sim/lanelet2_interface_ros.

Note that this is not the final version and it might still change a lot. We still plan to launch it this year, however.

**Comment by fkthi** [comment]
Thank you very much.
