### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by srirambadri** [fzi-forschungszentrum-informatik/Lanelet2#73]
Hi,

when I try to build manually I get an error for lanelet2_io. 

> /usr/bin/ld.gold: error: /usr/local/lib/libpugixml.a(pugixml.cpp.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC

I included the lines 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC" ) 
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC" ) 

to the CMakelists of the lanelet2_io package but the error persists. Do you know how to solve this error?

![image](https://user-images.githubusercontent.com/8626656/72442582-10444180-37ad-11ea-8ba8-7b440f75ac97.png)

**Comment by poggenhans** [comment]
You are linking the shared library from lanelet2_io with the static library pugixml. That usually requires that the static library is compiled with "-fPIC". The "recompile with -fPIC" does not refer to lanelet2 (that should use it anyways because its usually a shared library) but to pugixml itself.

You either have to build pugixml as a shared library, or you have to rebuilt it as a static library with "-fPIC".

**Comment by srirambadri** [comment]
thanks for the quick suggestion. I'll rebuild pugixml again
