### ISSUE TITLE
route->fullLane(...) behavior

### ISSUE THREAD

**Issue by 0xd1ma** [fzi-forschungszentrum-informatik/Lanelet2#78]
Hello, Fabian.

I'm trying to solve the problem of creating a set of unique global trajectories for an autonomous vehicle using your library.

the main issue is the behavior of the route->fullLane(...) method.

if
route = routingGraph->getRoute(10077, 10086, 0);
unique lanes obtained using route->fullLane(...) are as follows:

10077

144410 10134 13666 10133 139831 139834 10130 10129 10127 10125 10124 9978 10123 10025 10121 9981 10079 10016 13487 10145 9977 10089 10142 10140 10139 10107 10138 10137 10135 10086

144411 13070 13668

one lanelet before closing the cycle
route = routingGraph->getRoute(10077, 10065, 0);

144410 10134 13666 10133 139831 139834 10130 10129 10127 10125 10124 9978 10123 10025 10121 9981 10079 10016 13487 10145 9977 10089 10142 10140 10139 10107 10138 10137 10135 10086 10065 10084 10077

144411 13070 13668

neighbors
route = routingGraph->getRoute(10077, 10084, 0);

144410 10134 13666 10133 139831 139834 10130 10129 10127 10125 10124 9978 10123 10025 10121 9981 10079 10016 13487 10145 9977 10089 10142 10140 10139 10107 10138 10137 10135 10086 10065 10084 10077 

144411 13070 13668

is this the correct behavior of the route->fullLane(...) method?

map is attached

[map.zip](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/files/4116753/map.zip)

**Comment by poggenhans** [comment]
`fullLane` should behave as documented: If you query for a route where start and end are connected or overlap, the lanes within the route will be circular and will not end at the "end" lanelet.

In your case, lanelet2 determines lanelet 144410 as the beginning of the lane, because at this lanelet the lane diverges from 144411. If this split wouldn't exist, this lane would have no clear beginning and `fullLane` would return a lane that always begins at the lanelet you queried it with (but otherwise contains the same lanelets, just in a different order).
