### ISSUE TITLE
Link between lanelet and traffic lights

### ISSUE THREAD

**Issue by mitsudome-r** [fzi-forschungszentrum-informatik/Lanelet2#83]
I have two questions regarding traffic lights.

1. Are there any reasons that traffic light regulatory elements are associated to lanelets entering intersections? It seems to make more sense if it is linked to lanelets within intersection.
For example, you might want to look at different traffic lights depending on which direction you are turning.

2. Is there any way to express light patterns between different traffic lights within same intersection. I would like to know if traffic light of intersecting(conflicting) lanelets are red or green just by looking at traffic light linked to ego vehicle's lanelet.

**Comment by poggenhans** [comment]
> Are there any reasons that traffic light regulatory elements are associated to lanelets entering intersections?

There is no such requirement for traffic lights. You are probably referring to the respective requirement for right of way regulations. From the way we designed it, it would make sense to assign the regulatory element to the lanelet where the stop line is. This simplifies the reasoning about the relevance of the traffic light because it basically means "if you cross this lanelet when the traffic light is red, you did something wrong".

The case that there are two traffic lights for different directions that are relevant for the same lanelet seems unrealistic to me because that would mean that vehicles on the same lane have a green light but might be are blocked by other vehicles that currently have a red light for their intended direction. But I would be interested in a counterexample.

> Is there any way to express light patterns between different traffic lights within same intersection.

The regulatory elements we provide are a proposal from us which we believe to cover the usual use cases. We are aware that they could be biased by the way the regulations are expressed in Germany and that there could be different approaches for different countries. We have therefore designed regulatory elements in such a way that they are expandable and open for improvement.

Our traffic lights regulatory elements are not designed to carry relations about other traffic lights because for a normal road user that information is also not available. But you could simply design you own regulatory element that covers you needs.

**Comment by poggenhans** [comment]
This issue has been inactive for a while. I'm assuming the original question has been answered.
