### ISSUE TITLE
Calculate curvature of LineString

### ISSUE THREAD

**Issue by autonomobil** [fzi-forschungszentrum-informatik/Lanelet2#87]
Is there a function for calculating the curvature (probably Menger) of a LineString?

I know how to do it with 3 points, but maybe there is already a function for that..

reference: https://en.wikipedia.org/wiki/Menger_curvature

I see there's the function `maxCurveSpeed`, but it is not implemented yet.

**Comment by poggenhans** [comment]
Indeed, that function was somehow forgotten when we implemented the geometry part, and so far no one showed interest in porting that (and the function to compute the curvature) from lanelet1 (https://github.com/fzi-forschungszentrum-informatik/liblanelet/blob/master/src/liblanelet/Lanelet.cpp#L467).

We are always happy about a PR, If you are interested in implementing it. Otherwise we will most probably add it at some point, but it doesn't have a high priority for us.

**Comment by m-naumann** [comment]
Just to add, the function is already implemented is part of a validator. This could be replaced then: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_validation/src/validators/CurvatureTooBig.cpp#L21

**Comment by m-naumann** [comment]
See https://github.com/fzi-forschungszentrum-informatik/Lanelet2/commit/e9cc114f6676d8c6e8e1ddabfd21331cc9c4ec54

**Comment by autonomobil** [comment]
perfect, thanks!
